language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - boost-latest
          packages:
            - g++-4.9
            - libboost1.55-all-dev
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - boost-latest
          packages:
            - g++-5
            - libboost1.55-all-dev
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
            - boost-latest
          packages:
            - clang-3.6
            - libboost1.55-all-dev
      env:
        - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6"
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
            - boost-latest
          packages:
            - clang-3.7
            - libboost1.55-all-dev
      env:
        - MATRIX_EVAL="CC=clang-3.7 && CXX=clang++-3.7"

script:
  - mkdir build
  - cd build
  - cmake .. && make
